name: Check PR

on: [pull_request_target]
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: danger/danger-js@9.1.6
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile ./dangerfile-greeting.ts"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile ./dangerfile-invite.ts"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}          
