name: Check PR

<<<<<<< HEAD
<<<<<<< HEAD
on: [pull_request_target]
=======
on: [pull_request]
>>>>>>> a112c35... feat: update dangerfile
=======
on: [pull_request_target]
>>>>>>> 75b56ea... mhh
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: danger/danger-js@9.1.6
        env:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - run: yarn danger ci -d ./dangerfile-greeting.ts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - run: yarn danger ci -d ./dangerfile-invite.ts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}  
=======
          GITHUB_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
>>>>>>> 0d19546... feat: rename token
=======
          GITHUB_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
>>>>>>> 0e5bceb... feat: add token to env
=======
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 27dc8de... revert changes
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
<<<<<<< HEAD
>>>>>>> 8e13769... feat: add new token
      - run: yarn danger ci -d ./dangerfile-greeting.ts
=======
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
>>>>>>> 471e13b... feat: rename github token
      - uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile ./dangerfile-greeting.ts"
>>>>>>> f491426... feat: user other danger action type
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile ./dangerfile-invite.ts"
        env:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.DANGER_API_TOKEN }}          
>>>>>>> a112c35... feat: update dangerfile
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}          
>>>>>>> 0d19546... feat: rename token
=======
          GITHUB_TOKEN: ${{ secrets.DANGER_API_TOKEN }}          
>>>>>>> 0e5bceb... feat: add token to env
=======
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
>>>>>>> 27dc8de... revert changes
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}          
>>>>>>> 8e13769... feat: add new token
=======
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}          
>>>>>>> 471e13b... feat: rename github token
