name: Update Docs && Website

on: 
  push:
    branches:
      - "master"
    paths:
      - "schemas/fig.d.ts"

jobs:
  update_page:
    runs-on: "ubuntu-latest"
    env:
      UPDATE_SITE_TOKEN: ${{ secrets.UPDATE_PRIVATE_DOCS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: update docs
        run: |
          git clone https://withfig-bot:$UPDATE_SITE_TOKEN@github.com/withfig/public-site-nextjs.git
          cd public-site-nextjs

          curl https://fig.io/api/docs/parseDocs -o newDocs.zip

          unzip -o newDocs.zip -d docs/reference/

          rm -f newDocs.zip

          git config user.email "tim@withfig.com"
          git config user.name "Figbot"
<<<<<<< HEAD
          
          git add autocomplete/api.md
=======

          git add docs/reference/

<<<<<<< HEAD
>>>>>>> 4f57af5... feat: update docs action
          git commit -m "added updates to docs"
          git push origin main
=======
          git commit -m "added updates to docs" --allow-empty
          git push origin main --force
<<<<<<< HEAD
>>>>>>> 73898ca... revert change
=======
      - uses: actions/checkout@v2
      - name: update boilerplate
        run: |
          git clone https://withfig-bot:$UPDATE_SITE_TOKEN@github.com/withfig/autocomplete-boilerplate.git

          cp schemas/fig.d.ts autocomplete-boilerplate/schemas/fig.d.ts

          cd autocomplete-boilerplate

          git config user.email "tim@withfig.com"
          git config user.name "Figbot"

          git add schemas/fig.d.ts

          git commit -m "chore: sync schema changes" --allow-empty
          git push origin main --force
>>>>>>> 2a0eea6... feat: update boilerplate on schema changes
